name: OC action
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to install s2i
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: "Mona the Octocat"
      # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"
      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v1
      #   with:
      #     version: latest
      # - name: Run Hello World
      #   run: docker run hello-world
      # - uses: actions/checkout@master
      # - name: setup-go
      #   uses: actions/setup-go@v1
      #   with:
      #     go-version: "1.14.10" # The Go version to download (if necessary) and use.
      # - name: Test go
      #   run: echo $(go version)
      - name: Test s2i
        run: echo $(whereis curl)
      - name: Install s2i
        # run: GO111MODULE=on go get github.com/openshift/source-to-image/cmd/s2i@master
        run: |
          curl -Lfs -o source-to-image-v1.3.1-a5a77147-linux-amd64.tar.gz https://github.com/openshift/source-to-image/releases/download/v1.3.1/source-to-image-v1.3.1-a5a77147-linux-amd64.tar.gz
          sudo tar -xzf source-to-image-v1.3.1-a5a77147-linux-amd64.tar.gz
          sudo cp s2i /usr/local/bin/
          cd /usr/local/bin/
          chmod +x s2i
          s2i version
      - name: Test s2i
        run: echo $(whereis curl)
      # - run: |
      #     go version
      #     echo "Hello from go"
      #     echo ${GOPATH}
      #     go get github.com/openshift/source-to-image
      #     cd ${GOPATH}/src/github.com/openshift/source-to-image
      #     export PATH=$PATH:${GOPATH}/src/github.com/openshift/source-to-image/_output/local/bin/linux/amd64/
      #     hack/build-go.sh
      #     s2i version
